##########
# Config #
##########
reload-message: '&f[AnarchyCore] &7- config reloaded!'
###########
# illegal #
###########
PreventPlace: true
########
# Misc #
########
BedCheck:
  have: '&aYou have respawn'
  havent: "&cYou haven't respawn"
##############
# PreventLag #
##############
MiniSuppressor:
  enable: true
  message: "&cYou can't place redstone on the trapdoor"
##################
# Server Protect #
##################
GameModeLeft: true
GameModeProtect:
  enable: true
  kick-message: '&6You have disconnected from the server'
  whitelist:
    - 'sabzip'
OpLeft: true
OpProtect:
  enable: true
  kick-message: '&6You have disconnected from the server'
  whitelist:
    - 'sabzip'